import { Box, Button } from '@mui/material'
import Head from 'next/head'
import { useState } from 'react'
import { CSVLink } from 'react-csv'
import ExpensesTable from '../components/expensesTable'
import updateCategoriesMapping, { getTransformedExpensesFromCsv } from '../components/services/services'
import styles from '../styles/Home.module.css'
import { getCategories } from '../utils/utils'

export default function Home({ categories1, categories2 }) {
  const [records, setRecords] = useState([])

  const handleSubmit = async (event) => {
    const file = event.target.files[0]

    if (!file) {
      return
    }

    const expenses = await getTransformedExpensesFromCsv(file)
    setRecords(expenses);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Personal budget
        </h1>
        <Box m={4} display="flex" alignItems="center" justifyContent="flex-end" width="100%">
          <Form onSubmit={(event) => handleSubmit(event)} />
          <Box mx={2}>
            <CSVLink data={records} mx={2}><Button variant="contained" component="label" disabled={!records.length}>Export CSV</Button></CSVLink>
          </Box>
        </Box>
        <ExpensesTable data={records} categories1={categories1} categories2={categories2} handleChange={updateCategoriesMapping}/>
     </main>
    </div>
  )
}

export function Form({ onSubmit }) {

  return (
    <Button
      variant="contained"
      component="label"
    >
      Upload File
      <input
        type="file"
        hidden
        onChange={onSubmit}
      />
    </Button>
  )
}

export async function getServerSideProps(context) {
  const data = getCategories()
  return {
    props: {categories1: data.categories1, categories2: data.categories2}
  }
}
