import { Box, Button } from '@mui/material'
import Head from 'next/head'
import { useState } from 'react'
import { CSVLink } from 'react-csv'
import ExpensesTable from '../components/ExpensesTable'
import UploadCsv from '../components/UploadCsv'
import updateCategoriesMapping, { getTransformedExpensesFromCsv } from '../services/services'
import styles from '../styles/Home.module.css'
import { getCategories } from '../utils/utils'

export default function Home({ categories1, categories2 }) {
  const [records, setRecords] = useState([])
  const [error, setError] = useState('')

  const handleSubmit = async (event) => {
    const file = event.target.files[0]
    console.log('handle submit')
    if (!file) {
      return
    }

    console.log('calling api')
    const {data, error} = await getTransformedExpensesFromCsv(file)
    console.log('data ', data)
    console.log('error ', error)
    if (data) {
      setRecords(data);
    }
    if (error) {
      setError("Error: something wrong happened");
      console.log('Setting error')
    } else {
      setError('');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Personal budget
        </h1>
        <div>{error}</div>
        <Box m={4} display="flex" alignItems="center" justifyContent="flex-end" width="100%">
          <UploadCsv onSubmit={(event) => {
            console.log('onSubmit')
            handleSubmit(event)
          }} />
          <Box mx={2}>
            <CSVLink data={records} mx={2}>
              <Button 
                color="success"
                variant="contained" component="label" disabled={!records?.length}
              >Export CSV</Button>
            </CSVLink>
          </Box>
        </Box>
        <ExpensesTable data={records} categories1={categories1} categories2={categories2} handleChange={updateCategoriesMapping}/>
     </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const data = getCategories()
  return {
    props: {categories1: data.categories1, categories2: data.categories2}
  }
}
